export function generateNotebook(cells = [], { title = "Brain101 Analysis", libraries = [] } = {}) {
  const headerCell = {
    cell_type: "markdown",
    metadata: {},
    source: [
      `# ${title}\n`,
      "\n",
      "_Generated by [Brain101 Connectomics Explorer](https://github.com/wrgr/llm101/tree/main/brain101)_\n",
      "\n",
      libraries.length
        ? `**Install dependencies:**\n\`\`\`bash\npip install ${libraries.join(" ")}\n\`\`\`\n`
        : "",
    ].filter(Boolean),
  };

  const notebookCells = [headerCell, ...cells.map(toJupyterCell)];

  return {
    nbformat: 4,
    nbformat_minor: 5,
    metadata: {
      kernelspec: {
        display_name: "Python 3",
        language: "python",
        name: "python3",
      },
      language_info: {
        name: "python",
        version: "3.10.0",
      },
    },
    cells: notebookCells,
  };
}

function toJupyterCell({ cellType, source }) {
  const lines = source.split("\n").map((l, i, arr) =>
    i < arr.length - 1 ? l + "\n" : l
  );
  if (cellType === "markdown") {
    return { cell_type: "markdown", metadata: {}, source: lines };
  }
  return {
    cell_type: "code",
    execution_count: null,
    metadata: {},
    outputs: [],
    source: lines,
  };
}

export function downloadNotebook(notebookJson, filename = "brain101_analysis.ipynb") {
  const blob = new Blob([JSON.stringify(notebookJson, null, 2)], {
    type: "application/x-ipynb+json",
  });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
